name: Check and Trigger Package Builds (COPR)

on:
  schedule:
      - cron: '0 16 * * *'
  workflow_dispatch:
  
env:
    COPR_LOGIN: ${{ secrets.COPR_LOGIN }}
    COPR_TOKEN: ${{ secrets.COPR_TOKEN }}

jobs:
  check-for-updates:
    runs-on: ubuntu-latest
    container: fedora:latest
    
    steps:
      - name: Checkout master
        uses: actions/checkout@v4
        
      - name: Install packages
        run: dnf install -y copr-cli python3 python3-pip git
        
      - name: Check for Update and Trigger Build
        run: |
          pip install ghapi enhanced_versioning specfile
          python update_packages.py
